#!/usr/bin/env bash
set -e

echo "🚀 BetaLabs Web3 Workshop - Start Script"
echo "========================================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Make scripts executable
chmod +x setup.sh test.sh 2>/dev/null || true

# Config file to store deployment info
CONFIG_FILE=".workshop-config"

# Function to cleanup on exit
cleanup() {
    echo ""
    echo -e "${YELLOW}🛑 Shutting down...${NC}"
    if [ ! -z "$HARDHAT_PID" ]; then
        kill $HARDHAT_PID 2>/dev/null || true
    fi
    if [ ! -z "$WEB_PID" ]; then
        kill $WEB_PID 2>/dev/null || true
    fi
    exit
}

trap cleanup SIGINT SIGTERM

# Check if dependencies are installed
if [ ! -d "contracts/node_modules" ] || [ ! -d "web/node_modules" ]; then
    echo -e "${RED}❌ Dependencies not installed!${NC}"
    echo -e "${YELLOW}Run ./setup.sh first${NC}"
    exit 1
fi

# Check if there's an existing deployment
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
    echo -e "${CYAN}📋 Found existing deployment:${NC}"
    echo -e "   Contract: ${EXISTING_CONTRACT_ADDRESS:-not found}"
    echo ""
    read -p "Do you want to reuse the existing deployment? (y/n): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        REUSE_DEPLOYMENT=true
        CONTRACT_ADDRESS="$EXISTING_CONTRACT_ADDRESS"
        echo -e "${GREEN}✅ Reusing existing deployment${NC}"
    else
        REUSE_DEPLOYMENT=false
    fi
else
    REUSE_DEPLOYMENT=false
fi

echo -e "${BLUE}Step 1: Starting Hardhat Node...${NC}"
cd contracts
npm run node > ../hardhat.log 2>&1 &
HARDHAT_PID=$!
cd ..

echo "Waiting for Hardhat to start..."
sleep 3

if ! kill -0 $HARDHAT_PID 2>/dev/null; then
    echo -e "${RED}❌ Hardhat failed to start. Check hardhat.log${NC}"
    cat hardhat.log
    exit 1
fi

echo -e "${GREEN}✅ Hardhat node running (PID: $HARDHAT_PID)${NC}"

# Extract test accounts from Hardhat output
sleep 1
echo ""
echo -e "${CYAN}💰 Test Accounts Available:${NC}"
grep -A 1 "Account #0" hardhat.log | head -4 || echo "Check hardhat.log for account details"
echo ""

if [ "$REUSE_DEPLOYMENT" = false ]; then
    echo -e "${BLUE}Step 2: Deploying Smart Contract...${NC}"
    cd contracts
    DEPLOY_OUTPUT=$(npx hardhat run scripts/deploy.ts --network localhost 2>&1)
    echo "$DEPLOY_OUTPUT"

    # Extract contract address with multiple fallback patterns
    CONTRACT_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep -o "0x[a-fA-F0-9]\{40\}" | head -1)

    if [ -z "$CONTRACT_ADDRESS" ]; then
        echo -e "${RED}❌ Failed to extract contract address${NC}"
        echo "Deploy output was:"
        echo "$DEPLOY_OUTPUT"
        cleanup
    fi

    echo -e "${GREEN}✅ Contract deployed at: $CONTRACT_ADDRESS${NC}"
    
    # Save to config file
    echo "EXISTING_CONTRACT_ADDRESS=$CONTRACT_ADDRESS" > "../$CONFIG_FILE"
    
    cd ..
else
    echo -e "${BLUE}Step 2: Using Existing Contract...${NC}"
    echo -e "${GREEN}✅ Contract address: $CONTRACT_ADDRESS${NC}"
fi
echo ""

echo -e "${BLUE}Step 3: Updating Configuration Files...${NC}"

# Update web app constants
WEB_CONSTANTS="web/src/utils/constants.ts"
if [ -f "$WEB_CONSTANTS" ]; then
    # Create backup
    cp "$WEB_CONSTANTS" "${WEB_CONSTANTS}.bak"
    
    # Update the contract address
    sed -i "s|export const CONTRACT_ADDRESS = .*|export const CONTRACT_ADDRESS = \"$CONTRACT_ADDRESS\"; // Auto-updated by start.sh|" "$WEB_CONSTANTS"
    echo -e "${GREEN}  ✓ Updated web/src/utils/constants.ts${NC}"
else
    echo -e "${RED}  ✗ Warning: constants.ts not found${NC}"
fi

# Create/update .env file for registration script
REG_ENV="registration-script/.env"
cat > "$REG_ENV" << EOF
# Auto-generated by start.sh
RPC_URL=http://localhost:8545
# Using Account #1 to avoid MetaMask blocking Account #0
PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
CONTRACT_ADDRESS=$CONTRACT_ADDRESS

# Optional: Customize your student info
STUDENT_NAME=John Doe
STUDENT_ROLL=CS2024001
EOF

echo -e "${GREEN}  ✓ Created registration-script/.env${NC}"
echo ""

echo -e "${BLUE}Step 4: Starting Web Server...${NC}"
cd web
npm run dev -- --host 0.0.0.0 > ../web.log 2>&1 &
WEB_PID=$!
cd ..

echo "Waiting for web server to start..."
sleep 4

if ! kill -0 $WEB_PID 2>/dev/null; then
    echo -e "${RED}❌ Web server failed to start. Check web.log${NC}"
    tail -20 web.log
    cleanup
fi

# Extract actual port from web.log
WEB_PORT=$(grep -o "http://localhost:[0-9]*" web.log | head -1 | grep -o "[0-9]*$" || echo "5173")

echo -e "${GREEN}✅ Web server running (PID: $WEB_PID)${NC}"
echo ""

# Get local IP
LOCAL_IP=$(hostname -I | awk '{print $1}' || echo "localhost")

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}🎉 Workshop is Ready!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${CYAN}📊 Connection Information:${NC}"
echo ""
echo -e "${YELLOW}For Local Testing:${NC}"
echo "  🌐 Website:  http://localhost:${WEB_PORT}"
echo "  ⛓️  RPC URL:  http://localhost:8545"
echo ""
echo -e "${YELLOW}For Workshop Participants (LAN):${NC}"
echo "  🌐 Website:  http://${LOCAL_IP}:${WEB_PORT}"
echo "  ⛓️  RPC URL:  http://${LOCAL_IP}:8545"
echo ""
echo -e "${YELLOW}Smart Contract:${NC}"
echo "  📜 Address:  ${CONTRACT_ADDRESS}"
echo ""
echo -e "${YELLOW}Network Configuration:${NC}"
echo "  🔗 Chain ID: 1337"
echo "  💰 Currency: ETH (test)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${CYAN}📝 Quick Test (in another terminal):${NC}"
echo ""
echo "  # Test with JavaScript/TypeScript:"
echo "  cd registration-script"
echo "  npm start"
echo ""
echo "  # Or test with Python:"
echo "  cd registration-script"
echo "  pip install -r requirements.txt"
echo "  python register.py"
echo ""
echo -e "${CYAN}🌐 MetaMask Setup:${NC}"
echo "  1. Add Network:"
echo "     - Network Name: Workshop"
echo "     - RPC URL: http://${LOCAL_IP}:8545"
echo "     - Chain ID: 1337"
echo "     - Symbol: ETH"
echo ""
echo "  2. Import Test Account:"
echo "     - Use Account #1 (Account #0 is blocked by MetaMask)"
echo "     - Private Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
echo "     - (Check hardhat.log for more accounts)"
echo ""
echo -e "${RED}Press Ctrl+C to stop all services${NC}"
echo ""

# Save info to a file for easy reference
cat > workshop-info.txt << EOF
BetaLabs Web3 Workshop - Connection Info
=========================================

Website (Local):     http://localhost:${WEB_PORT}
Website (LAN):       http://${LOCAL_IP}:${WEB_PORT}

RPC URL (Local):     http://localhost:8545
RPC URL (LAN):       http://${LOCAL_IP}:8545

Contract Address:    ${CONTRACT_ADDRESS}
Chain ID:            1337

Test Account #1 (recommended - Account #0 is blocked by MetaMask):
  Address:      0x70997970C51812dc3A010C7d01b50e0d17dc79C8
  Private Key:  0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

For more accounts, see hardhat.log
EOF

echo -e "${GREEN}✅ Connection info saved to workshop-info.txt${NC}"
echo ""

# Keep script running and show logs
tail -f hardhat.log web.log
